name: bloodbank
description: A comprehensive blood bank management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  url_launcher: ^6.2.1
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
